export const jobdata = [
  {
    "job_id": "PAY88557",
    "employer_name": "PayPal",
    "employer_logo": "https://logo.clearbit.com/paypal.com",
    "employer_website": "https://www.paypal.com",
    "job_title": "Full Stack Engineer",
    "job_apply_link": "https://www.paypal.com/careers/full-stack-engineer-6981",
    "job_description": "Join PayPal's dynamic team as a Full Stack Engineer in Miami, FL. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Miami, FL",
    "job_city": "Miami",
    "job_state": "FL",
    "job_country": "US"
  },
  {
    "job_id": "IBM90604",
    "employer_name": "IBM",
    "employer_logo": "https://logo.clearbit.com/ibm.com",
    "employer_website": "https://www.ibm.com",
    "job_title": "Product Manager",
    "job_apply_link": "https://www.ibm.com/careers/product-manager-4089",
    "job_description": "Join IBM's dynamic team as a Product Manager in Los Angeles, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Los Angeles, CA",
    "job_city": "Los Angeles",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "PAY43445",
    "employer_name": "PayPal",
    "employer_logo": "https://logo.clearbit.com/paypal.com",
    "employer_website": "https://www.paypal.com",
    "job_title": "Backend Developer",
    "job_apply_link": "https://www.paypal.com/careers/backend-developer-7060",
    "job_description": "Join PayPal's dynamic team as a Backend Developer in San Francisco, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "San Francisco, CA",
    "job_city": "San Francisco",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "APP70290",
    "employer_name": "Apple",
    "employer_logo": "https://logo.clearbit.com/apple.com",
    "employer_website": "https://www.apple.com",
    "job_title": "Software Engineer",
    "job_apply_link": "https://www.apple.com/careers/software-engineer-6943",
    "job_description": "Join Apple's dynamic team as a Software Engineer in Boston, MA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Boston, MA",
    "job_city": "Boston",
    "job_state": "MA",
    "job_country": "US"
  },
  {
    "job_id": "DRO19951",
    "employer_name": "Dropbox",
    "employer_logo": "https://logo.clearbit.com/dropbox.com",
    "employer_website": "https://www.dropbox.com",
    "job_title": "Full Stack Engineer",
    "job_apply_link": "https://www.dropbox.com/careers/full-stack-engineer-7412",
    "job_description": "Join Dropbox's dynamic team as a Full Stack Engineer in Seattle, WA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Seattle, WA",
    "job_city": "Seattle",
    "job_state": "WA",
    "job_country": "US"
  },
  {
    "job_id": "ZOO10594",
    "employer_name": "Zoom",
    "employer_logo": "https://logo.clearbit.com/zoom.com",
    "employer_website": "https://www.zoom.com",
    "job_title": "Cloud Engineer",
    "job_apply_link": "https://www.zoom.com/careers/cloud-engineer-6334",
    "job_description": "Join Zoom's dynamic team as a Cloud Engineer in Miami, FL. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Miami, FL",
    "job_city": "Miami",
    "job_state": "FL",
    "job_country": "US"
  },
  {
    "job_id": "APP80404",
    "employer_name": "Apple",
    "employer_logo": "https://logo.clearbit.com/apple.com",
    "employer_website": "https://www.apple.com",
    "job_title": "Software Engineer",
    "job_apply_link": "https://www.apple.com/careers/software-engineer-6492",
    "job_description": "Join Apple's dynamic team as a Software Engineer in Seattle, WA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Seattle, WA",
    "job_city": "Seattle",
    "job_state": "WA",
    "job_country": "US"
  },
  {
    "job_id": "AMA97917",
    "employer_name": "Amazon",
    "employer_logo": "https://logo.clearbit.com/amazon.com",
    "employer_website": "https://www.amazon.com",
    "job_title": "Cloud Engineer",
    "job_apply_link": "https://www.amazon.com/careers/cloud-engineer-3221",
    "job_description": "Join Amazon's dynamic team as a Cloud Engineer in Miami, FL. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Miami, FL",
    "job_city": "Miami",
    "job_state": "FL",
    "job_country": "US"
  },
  {
    "job_id": "TES21805",
    "employer_name": "Tesla",
    "employer_logo": "https://logo.clearbit.com/tesla.com",
    "employer_website": "https://www.tesla.com",
    "job_title": "QA Engineer",
    "job_apply_link": "https://www.tesla.com/careers/qa-engineer-4282",
    "job_description": "Join Tesla's dynamic team as a QA Engineer in Miami, FL. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Miami, FL",
    "job_city": "Miami",
    "job_state": "FL",
    "job_country": "US"
  },
  {
    "job_id": "UBE99622",
    "employer_name": "Uber",
    "employer_logo": "https://logo.clearbit.com/uber.com",
    "employer_website": "https://www.uber.com",
    "job_title": "Product Manager",
    "job_apply_link": "https://www.uber.com/careers/product-manager-1179",
    "job_description": "Join Uber's dynamic team as a Product Manager in San Francisco, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "San Francisco, CA",
    "job_city": "San Francisco",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "TES42600",
    "employer_name": "Tesla",
    "employer_logo": "https://logo.clearbit.com/tesla.com",
    "employer_website": "https://www.tesla.com",
    "job_title": "Backend Developer",
    "job_apply_link": "https://www.tesla.com/careers/backend-developer-2229",
    "job_description": "Join Tesla's dynamic team as a Backend Developer in Los Angeles, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Los Angeles, CA",
    "job_city": "Los Angeles",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "APP94424",
    "employer_name": "Apple",
    "employer_logo": "https://logo.clearbit.com/apple.com",
    "employer_website": "https://www.apple.com",
    "job_title": "Machine Learning Engineer",
    "job_apply_link": "https://www.apple.com/careers/machine-learning-engineer-7816",
    "job_description": "Join Apple's dynamic team as a Machine Learning Engineer in Seattle, WA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Seattle, WA",
    "job_city": "Seattle",
    "job_state": "WA",
    "job_country": "US"
  },
  {
    "job_id": "SPO40779",
    "employer_name": "Spotify",
    "employer_logo": "https://logo.clearbit.com/spotify.com",
    "employer_website": "https://www.spotify.com",
    "job_title": "Software Engineer",
    "job_apply_link": "https://www.spotify.com/careers/software-engineer-8741",
    "job_description": "Join Spotify's dynamic team as a Software Engineer in Los Angeles, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Los Angeles, CA",
    "job_city": "Los Angeles",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "AIR95888",
    "employer_name": "Airbnb",
    "employer_logo": "https://logo.clearbit.com/airbnb.com",
    "employer_website": "https://www.airbnb.com",
    "job_title": "Cloud Engineer",
    "job_apply_link": "https://www.airbnb.com/careers/cloud-engineer-3280",
    "job_description": "Join Airbnb's dynamic team as a Cloud Engineer in Miami, FL. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Miami, FL",
    "job_city": "Miami",
    "job_state": "FL",
    "job_country": "US"
  },
  {
    "job_id": "SAL38333",
    "employer_name": "Salesforce",
    "employer_logo": "https://logo.clearbit.com/salesforce.com",
    "employer_website": "https://www.salesforce.com",
    "job_title": "Cloud Engineer",
    "job_apply_link": "https://www.salesforce.com/careers/cloud-engineer-1453",
    "job_description": "Join Salesforce's dynamic team as a Cloud Engineer in Denver, CO. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Denver, CO",
    "job_city": "Denver",
    "job_state": "CO",
    "job_country": "US"
  },
  {
    "job_id": "SPO89983",
    "employer_name": "Spotify",
    "employer_logo": "https://logo.clearbit.com/spotify.com",
    "employer_website": "https://www.spotify.com",
    "job_title": "DevOps Engineer",
    "job_apply_link": "https://www.spotify.com/careers/devops-engineer-2420",
    "job_description": "Join Spotify's dynamic team as a DevOps Engineer in Miami, FL. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Miami, FL",
    "job_city": "Miami",
    "job_state": "FL",
    "job_country": "US"
  },
  {
    "job_id": "AIR90150",
    "employer_name": "Airbnb",
    "employer_logo": "https://logo.clearbit.com/airbnb.com",
    "employer_website": "https://www.airbnb.com",
    "job_title": "Product Manager",
    "job_apply_link": "https://www.airbnb.com/careers/product-manager-2913",
    "job_description": "Join Airbnb's dynamic team as a Product Manager in Austin, TX. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Austin, TX",
    "job_city": "Austin",
    "job_state": "TX",
    "job_country": "US"
  },
  {
    "job_id": "STR84886",
    "employer_name": "Stripe",
    "employer_logo": "https://logo.clearbit.com/stripe.com",
    "employer_website": "https://www.stripe.com",
    "job_title": "Software Engineer",
    "job_apply_link": "https://www.stripe.com/careers/software-engineer-8297",
    "job_description": "Join Stripe's dynamic team as a Software Engineer in Austin, TX. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Austin, TX",
    "job_city": "Austin",
    "job_state": "TX",
    "job_country": "US"
  },
  {
    "job_id": "NET84425",
    "employer_name": "Netflix",
    "employer_logo": "https://logo.clearbit.com/netflix.com",
    "employer_website": "https://www.netflix.com",
    "job_title": "Machine Learning Engineer",
    "job_apply_link": "https://www.netflix.com/careers/machine-learning-engineer-7589",
    "job_description": "Join Netflix's dynamic team as a Machine Learning Engineer in Denver, CO. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Denver, CO",
    "job_city": "Denver",
    "job_state": "CO",
    "job_country": "US"
  },
  {
    "job_id": "ZOO56689",
    "employer_name": "Zoom",
    "employer_logo": "https://logo.clearbit.com/zoom.com",
    "employer_website": "https://www.zoom.com",
    "job_title": "Software Engineer",
    "job_apply_link": "https://www.zoom.com/careers/software-engineer-9006",
    "job_description": "Join Zoom's dynamic team as a Software Engineer in New York, NY. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "New York, NY",
    "job_city": "New York",
    "job_state": "NY",
    "job_country": "US"
  },
  {
    "job_id": "AMA85207",
    "employer_name": "Amazon",
    "employer_logo": "https://logo.clearbit.com/amazon.com",
    "employer_website": "https://www.amazon.com",
    "job_title": "Full Stack Engineer",
    "job_apply_link": "https://www.amazon.com/careers/full-stack-engineer-9530",
    "job_description": "Join Amazon's dynamic team as a Full Stack Engineer in San Francisco, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "San Francisco, CA",
    "job_city": "San Francisco",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "ORA24054",
    "employer_name": "Oracle",
    "employer_logo": "https://logo.clearbit.com/oracle.com",
    "employer_website": "https://www.oracle.com",
    "job_title": "Full Stack Engineer",
    "job_apply_link": "https://www.oracle.com/careers/full-stack-engineer-5505",
    "job_description": "Join Oracle's dynamic team as a Full Stack Engineer in New York, NY. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "New York, NY",
    "job_city": "New York",
    "job_state": "NY",
    "job_country": "US"
  },
  {
    "job_id": "MET22838",
    "employer_name": "Meta",
    "employer_logo": "https://logo.clearbit.com/meta.com",
    "employer_website": "https://www.meta.com",
    "job_title": "Software Engineer",
    "job_apply_link": "https://www.meta.com/careers/software-engineer-5372",
    "job_description": "Join Meta's dynamic team as a Software Engineer in Los Angeles, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Los Angeles, CA",
    "job_city": "Los Angeles",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "NET25932",
    "employer_name": "Netflix",
    "employer_logo": "https://logo.clearbit.com/netflix.com",
    "employer_website": "https://www.netflix.com",
    "job_title": "Frontend Developer",
    "job_apply_link": "https://www.netflix.com/careers/frontend-developer-2338",
    "job_description": "Join Netflix's dynamic team as a Frontend Developer in Seattle, WA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Seattle, WA",
    "job_city": "Seattle",
    "job_state": "WA",
    "job_country": "US"
  },
  {
    "job_id": "PAY41936",
    "employer_name": "PayPal",
    "employer_logo": "https://logo.clearbit.com/paypal.com",
    "employer_website": "https://www.paypal.com",
    "job_title": "Backend Developer",
    "job_apply_link": "https://www.paypal.com/careers/backend-developer-6391",
    "job_description": "Join PayPal's dynamic team as a Backend Developer in San Francisco, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "San Francisco, CA",
    "job_city": "San Francisco",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "SPO36215",
    "employer_name": "Spotify",
    "employer_logo": "https://logo.clearbit.com/spotify.com",
    "employer_website": "https://www.spotify.com",
    "job_title": "Full Stack Engineer",
    "job_apply_link": "https://www.spotify.com/careers/full-stack-engineer-8502",
    "job_description": "Join Spotify's dynamic team as a Full Stack Engineer in Miami, FL. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Miami, FL",
    "job_city": "Miami",
    "job_state": "FL",
    "job_country": "US"
  },
  {
    "job_id": "ORA91504",
    "employer_name": "Oracle",
    "employer_logo": "https://logo.clearbit.com/oracle.com",
    "employer_website": "https://www.oracle.com",
    "job_title": "Frontend Developer",
    "job_apply_link": "https://www.oracle.com/careers/frontend-developer-1912",
    "job_description": "Join Oracle's dynamic team as a Frontend Developer in New York, NY. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "New York, NY",
    "job_city": "New York",
    "job_state": "NY",
    "job_country": "US"
  },
  {
    "job_id": "PAY50310",
    "employer_name": "PayPal",
    "employer_logo": "https://logo.clearbit.com/paypal.com",
    "employer_website": "https://www.paypal.com",
    "job_title": "Backend Developer",
    "job_apply_link": "https://www.paypal.com/careers/backend-developer-6768",
    "job_description": "Join PayPal's dynamic team as a Backend Developer in Atlanta, GA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Atlanta, GA",
    "job_city": "Atlanta",
    "job_state": "GA",
    "job_country": "US"
  },
  {
    "job_id": "NVI51677",
    "employer_name": "Nvidia",
    "employer_logo": "https://logo.clearbit.com/nvidia.com",
    "employer_website": "https://www.nvidia.com",
    "job_title": "Backend Developer",
    "job_apply_link": "https://www.nvidia.com/careers/backend-developer-5519",
    "job_description": "Join Nvidia's dynamic team as a Backend Developer in Chicago, IL. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Chicago, IL",
    "job_city": "Chicago",
    "job_state": "IL",
    "job_country": "US"
  },
  {
    "job_id": "APP28508",
    "employer_name": "Apple",
    "employer_logo": "https://logo.clearbit.com/apple.com",
    "employer_website": "https://www.apple.com",
    "job_title": "Full Stack Engineer",
    "job_apply_link": "https://www.apple.com/careers/full-stack-engineer-2042",
    "job_description": "Join Apple's dynamic team as a Full Stack Engineer in Austin, TX. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Austin, TX",
    "job_city": "Austin",
    "job_state": "TX",
    "job_country": "US"
  },
  {
    "job_id": "PAY71504",
    "employer_name": "PayPal",
    "employer_logo": "https://logo.clearbit.com/paypal.com",
    "employer_website": "https://www.paypal.com",
    "job_title": "Full Stack Engineer",
    "job_apply_link": "https://www.paypal.com/careers/full-stack-engineer-7004",
    "job_description": "Join PayPal's dynamic team as a Full Stack Engineer in New York, NY. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "New York, NY",
    "job_city": "New York",
    "job_state": "NY",
    "job_country": "US"
  },
  {
    "job_id": "UBE42793",
    "employer_name": "Uber",
    "employer_logo": "https://logo.clearbit.com/uber.com",
    "employer_website": "https://www.uber.com",
    "job_title": "Software Engineer",
    "job_apply_link": "https://www.uber.com/careers/software-engineer-3806",
    "job_description": "Join Uber's dynamic team as a Software Engineer in Austin, TX. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Austin, TX",
    "job_city": "Austin",
    "job_state": "TX",
    "job_country": "US"
  },
  {
    "job_id": "STR54231",
    "employer_name": "Stripe",
    "employer_logo": "https://logo.clearbit.com/stripe.com",
    "employer_website": "https://www.stripe.com",
    "job_title": "Full Stack Engineer",
    "job_apply_link": "https://www.stripe.com/careers/full-stack-engineer-6310",
    "job_description": "Join Stripe's dynamic team as a Full Stack Engineer in Miami, FL. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Miami, FL",
    "job_city": "Miami",
    "job_state": "FL",
    "job_country": "US"
  },
  {
    "job_id": "NET96796",
    "employer_name": "Netflix",
    "employer_logo": "https://logo.clearbit.com/netflix.com",
    "employer_website": "https://www.netflix.com",
    "job_title": "Frontend Developer",
    "job_apply_link": "https://www.netflix.com/careers/frontend-developer-2621",
    "job_description": "Join Netflix's dynamic team as a Frontend Developer in Los Angeles, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Los Angeles, CA",
    "job_city": "Los Angeles",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "AMA98069",
    "employer_name": "Amazon",
    "employer_logo": "https://logo.clearbit.com/amazon.com",
    "employer_website": "https://www.amazon.com",
    "job_title": "Backend Developer",
    "job_apply_link": "https://www.amazon.com/careers/backend-developer-9905",
    "job_description": "Join Amazon's dynamic team as a Backend Developer in New York, NY. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "New York, NY",
    "job_city": "New York",
    "job_state": "NY",
    "job_country": "US"
  },
  {
    "job_id": "STR52789",
    "employer_name": "Stripe",
    "employer_logo": "https://logo.clearbit.com/stripe.com",
    "employer_website": "https://www.stripe.com",
    "job_title": "Frontend Developer",
    "job_apply_link": "https://www.stripe.com/careers/frontend-developer-5324",
    "job_description": "Join Stripe's dynamic team as a Frontend Developer in Miami, FL. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Miami, FL",
    "job_city": "Miami",
    "job_state": "FL",
    "job_country": "US"
  },
  {
    "job_id": "GOO22721",
    "employer_name": "Google",
    "employer_logo": "https://logo.clearbit.com/google.com",
    "employer_website": "https://www.google.com",
    "job_title": "Software Engineer",
    "job_apply_link": "https://www.google.com/careers/software-engineer-5032",
    "job_description": "Join Google's dynamic team as a Software Engineer in Austin, TX. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Austin, TX",
    "job_city": "Austin",
    "job_state": "TX",
    "job_country": "US"
  },
  {
    "job_id": "NVI26410",
    "employer_name": "Nvidia",
    "employer_logo": "https://logo.clearbit.com/nvidia.com",
    "employer_website": "https://www.nvidia.com",
    "job_title": "Data Scientist",
    "job_apply_link": "https://www.nvidia.com/careers/data-scientist-4238",
    "job_description": "Join Nvidia's dynamic team as a Data Scientist in Los Angeles, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Los Angeles, CA",
    "job_city": "Los Angeles",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "ORA58055",
    "employer_name": "Oracle",
    "employer_logo": "https://logo.clearbit.com/oracle.com",
    "employer_website": "https://www.oracle.com",
    "job_title": "Machine Learning Engineer",
    "job_apply_link": "https://www.oracle.com/careers/machine-learning-engineer-3963",
    "job_description": "Join Oracle's dynamic team as a Machine Learning Engineer in Seattle, WA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Seattle, WA",
    "job_city": "Seattle",
    "job_state": "WA",
    "job_country": "US"
  },
  {
    "job_id": "IBM74222",
    "employer_name": "IBM",
    "employer_logo": "https://logo.clearbit.com/ibm.com",
    "employer_website": "https://www.ibm.com",
    "job_title": "Frontend Developer",
    "job_apply_link": "https://www.ibm.com/careers/frontend-developer-6536",
    "job_description": "Join IBM's dynamic team as a Frontend Developer in Los Angeles, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Los Angeles, CA",
    "job_city": "Los Angeles",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "ORA68524",
    "employer_name": "Oracle",
    "employer_logo": "https://logo.clearbit.com/oracle.com",
    "employer_website": "https://www.oracle.com",
    "job_title": "DevOps Engineer",
    "job_apply_link": "https://www.oracle.com/careers/devops-engineer-7025",
    "job_description": "Join Oracle's dynamic team as a DevOps Engineer in Los Angeles, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Los Angeles, CA",
    "job_city": "Los Angeles",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "DRO17761",
    "employer_name": "Dropbox",
    "employer_logo": "https://logo.clearbit.com/dropbox.com",
    "employer_website": "https://www.dropbox.com",
    "job_title": "Frontend Developer",
    "job_apply_link": "https://www.dropbox.com/careers/frontend-developer-2299",
    "job_description": "Join Dropbox's dynamic team as a Frontend Developer in Seattle, WA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Seattle, WA",
    "job_city": "Seattle",
    "job_state": "WA",
    "job_country": "US"
  },
  {
    "job_id": "MET13926",
    "employer_name": "Meta",
    "employer_logo": "https://logo.clearbit.com/meta.com",
    "employer_website": "https://www.meta.com",
    "job_title": "QA Engineer",
    "job_apply_link": "https://www.meta.com/careers/qa-engineer-3347",
    "job_description": "Join Meta's dynamic team as a QA Engineer in Seattle, WA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Seattle, WA",
    "job_city": "Seattle",
    "job_state": "WA",
    "job_country": "US"
  },
  {
    "job_id": "AIR21982",
    "employer_name": "Airbnb",
    "employer_logo": "https://logo.clearbit.com/airbnb.com",
    "employer_website": "https://www.airbnb.com",
    "job_title": "Cloud Engineer",
    "job_apply_link": "https://www.airbnb.com/careers/cloud-engineer-5781",
    "job_description": "Join Airbnb's dynamic team as a Cloud Engineer in San Francisco, CA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "San Francisco, CA",
    "job_city": "San Francisco",
    "job_state": "CA",
    "job_country": "US"
  },
  {
    "job_id": "GOO39658",
    "employer_name": "Google",
    "employer_logo": "https://logo.clearbit.com/google.com",
    "employer_website": "https://www.google.com",
    "job_title": "Backend Developer",
    "job_apply_link": "https://www.google.com/careers/backend-developer-1302",
    "job_description": "Join Google's dynamic team as a Backend Developer in Denver, CO. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Denver, CO",
    "job_city": "Denver",
    "job_state": "CO",
    "job_country": "US"
  },
  {
    "job_id": "ADO73453",
    "employer_name": "Adobe",
    "employer_logo": "https://logo.clearbit.com/adobe.com",
    "employer_website": "https://www.adobe.com",
    "job_title": "Full Stack Engineer",
    "job_apply_link": "https://www.adobe.com/careers/full-stack-engineer-2936",
    "job_description": "Join Adobe's dynamic team as a Full Stack Engineer in Miami, FL. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Miami, FL",
    "job_city": "Miami",
    "job_state": "FL",
    "job_country": "US"
  },
  {
    "job_id": "APP71203",
    "employer_name": "Apple",
    "employer_logo": "https://logo.clearbit.com/apple.com",
    "employer_website": "https://www.apple.com",
    "job_title": "Full Stack Engineer",
    "job_apply_link": "https://www.apple.com/careers/full-stack-engineer-4713",
    "job_description": "Join Apple's dynamic team as a Full Stack Engineer in Seattle, WA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Seattle, WA",
    "job_city": "Seattle",
    "job_state": "WA",
    "job_country": "US"
  },
  {
    "job_id": "ADO62273",
    "employer_name": "Adobe",
    "employer_logo": "https://logo.clearbit.com/adobe.com",
    "employer_website": "https://www.adobe.com",
    "job_title": "QA Engineer",
    "job_apply_link": "https://www.adobe.com/careers/qa-engineer-6349",
    "job_description": "Join Adobe's dynamic team as a QA Engineer in Denver, CO. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Denver, CO",
    "job_city": "Denver",
    "job_state": "CO",
    "job_country": "US"
  },
  {
    "job_id": "IBM39393",
    "employer_name": "IBM",
    "employer_logo": "https://logo.clearbit.com/ibm.com",
    "employer_website": "https://www.ibm.com",
    "job_title": "DevOps Engineer",
    "job_apply_link": "https://www.ibm.com/careers/devops-engineer-3399",
    "job_description": "Join IBM's dynamic team as a DevOps Engineer in Boston, MA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Boston, MA",
    "job_city": "Boston",
    "job_state": "MA",
    "job_country": "US"
  },
  {
    "job_id": "ORA26581",
    "employer_name": "Oracle",
    "employer_logo": "https://logo.clearbit.com/oracle.com",
    "employer_website": "https://www.oracle.com",
    "job_title": "QA Engineer",
    "job_apply_link": "https://www.oracle.com/careers/qa-engineer-7901",
    "job_description": "Join Oracle's dynamic team as a QA Engineer in Boston, MA. You'll work on modern technologies in a fast-paced environment. We're looking for innovative thinkers passionate about building high-quality software.",
    "job_employment_type": "FULLTIME",
    "job_employment_type_text": "Full-time",
    "job_location": "Boston, MA",
    "job_city": "Boston",
    "job_state": "MA",
    "job_country": "US"
  }
]